#ifndef _ENCLAVE_HELPER_FUNCIONS_H_
#define _ENCLAVE_HELPER_FUNCTIONS_H_

#define PARSE_HELPER_NO_MOD 0
#define PARSE_HELPER_MOD_TYPE_TAG 1
#define PARSE_HELPER_MOD_MSG_TYPE_VAL_LO 2
#define PARSE_HELPER_MOD_MSG_TYPE_VAL_HI 3
#define PARSE_HELPER_MOD_REQ_TYPE_VAL_LO 4
#define PARSE_HELPER_MOD_REQ_TYPE_VAL_HI 5
#define PARSE_HELPER_MOD_KEY_ID_TAG 6
#define PARSE_HELPER_MOD_DATA_TAG 7
#define PARSE_HELPER_MOD_STATUS_TAG 8

#define MSG_TEST_SUCCESS 0

#define MSG_TEST_SETUP_ERROR -1;

#define MSG_TEST_CREATE_ERROR -2

#define MSG_TEST_PARAM_HANDLING_OK -3
#define MSG_TEST_PARAM_HANDLING_ERROR -4

#define MSG_TEST_SIGN_FAILURE -5
#define MSG_TEST_INVALID_SIGN_RESULT -6

#define MSG_TEST_VERIFY_FAILURE -7

#define MSG_TEST_PARSE_INVALID -8

#endif
