#ifndef _ENCLAVE_HELPER_FUNCIONS_H_
#define _ENCLAVE_HELPER_FUNCTIONS_H_

#define MSG_TEST_SUCCESS 0

#define MSG_TEST_SETUP_ERROR 1;

#define MSG_TEST_PARAM_HANDLING_OK 2
#define MSG_TEST_PARAM_HANDLING_ERROR 3

#define MSG_TEST_SIGN_FAILURE 4
#define MSG_TEST_INVALID_SIGN_RESULT 5

#define MSG_TEST_VERIFY_FAILURE 6

#endif
