#ifndef _ENCLAVE_HELPER_FUNCIONS_H_
#define _ENCLAVE_HELPER_FUNCTIONS_H_

#define SIGN_TEST_SUCCESS 0
#define SIGN_TEST_FAILURE 1
#define SIGN_TEST_INVALID_RESULT 2
#define SIGN_TEST_INVALID_DER_CERT 3
#define SIGN_TEST_INVALID_DER_PRIV 4
#define SIGN_TEST_PARSE_ERROR 5

#endif
